### ISSUE TITLE
文件地址过期,报错

### ISSUE THREAD

**Issue by Lsoland** [jason-king123/ZHIHUISHU-Auto-Answer-Assistant#3]
首先给的chPPOCR地址已经过期,v4的onnx已经找不到了,必须手动去其他地方下载复制粘贴才能使用
做完这些之后,填入地址报出错误
Traceback (most recent call last):
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 55, in binary_paths
    return self._run(args)
           ^^^^^^^^^^^^^^^
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 129, in _run
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: D:\Software\python\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --language-binding python --output json; code: 65
{'code': 65, 'message': 'error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)', 'driver_path': '', 'browser_path': ''}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\Develop\github\ZHIHUISHU-Auto-Answer-Assistant\auto_answer_question.py", line 158, in <module>     
    main(url)
  File "d:\Develop\github\ZHIHUISHU-Auto-Answer-Assistant\auto_answer_question.py", line 150, in main
    driver = get_driver(url)
             ^^^^^^^^^^^^^^^
  File "d:\Develop\github\ZHIHUISHU-Auto-Answer-Assistant\auto_answer_question.py", line 36, in get_driver    
    driver = webdriver.Chrome(options=options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__    
    super().__init__(
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__  
    if finder.get_browser_path():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]        
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\Software\python\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
on on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by king-wang123** [comment]
不好意思，我没太懂`给的chPPOCR地址已经过期,v4的onnx已经找不到了`具体指的是什么意思，

至于下面的报错信息
```go
error sending request for url (https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json)
```
是Selenium 库访问不了这个 URL下载 ChromeDriver，可以在网上看一下selenium使用教程手动配置一下ChromeDriver

**Comment by Lsoland** [comment]
https://huggingface.co/breezedeus/cnstd-cnocr-models/tree/main/models/cnstd/1.2
这个页面已经没有v4了,我是在其他库找到的
